// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtOoD-4HHaTtlNNHK3hD8EUDURqwsYc7o',
    appId: '1:736667616620:web:e7206c139d60afb6a69f49',
    messagingSenderId: '736667616620',
    projectId: 'energy-audit-tool-64552',
    authDomain: 'energy-audit-tool-64552.firebaseapp.com',
    storageBucket: 'energy-audit-tool-64552.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAMxXjFPWTxn7qyGoNTVzShVhq8oXgTiY',
    appId: '1:736667616620:android:5c25879a88a7fd97a69f49',
    messagingSenderId: '736667616620',
    projectId: 'energy-audit-tool-64552',
    storageBucket: 'energy-audit-tool-64552.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEZDRkWLbCEVpOhvEG37H4H4K-TnhTdlM',
    appId: '1:736667616620:ios:0097006c623486d5a69f49',
    messagingSenderId: '736667616620',
    projectId: 'energy-audit-tool-64552',
    storageBucket: 'energy-audit-tool-64552.firebasestorage.app',
    iosBundleId: 'com.example.energyAuditTool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEZDRkWLbCEVpOhvEG37H4H4K-TnhTdlM',
    appId: '1:736667616620:ios:0097006c623486d5a69f49',
    messagingSenderId: '736667616620',
    projectId: 'energy-audit-tool-64552',
    storageBucket: 'energy-audit-tool-64552.firebasestorage.app',
    iosBundleId: 'com.example.energyAuditTool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtOoD-4HHaTtlNNHK3hD8EUDURqwsYc7o',
    appId: '1:736667616620:web:55218652a087c360a69f49',
    messagingSenderId: '736667616620',
    projectId: 'energy-audit-tool-64552',
    authDomain: 'energy-audit-tool-64552.firebaseapp.com',
    storageBucket: 'energy-audit-tool-64552.firebasestorage.app',
  );
}
